name: pipeline 
channels:
  - bioconda
  - conda-forge
dependencies:
  - python
  - mamba
  - snakemake
  - ncbi-datasets-cli
  - jinja2
  - minimap2
  - bowtie
  - bowtie2
  - blast
  - meme
  - imagemagick
  - pandas
  - openpyxl
  - biopython
  - samtools
  - bedtools
  - pyyaml



