# docker-compose.yml
version: '3.8'

services:
  rabbit_ig:
    build: .
    ports:
      - "5004:5004"
    command: gunicorn --chdir /app/rabbit_ig_results/flask --bind 0.0.0.0:5004 app:app

  rabbit_tr:
    build: .
    ports:
      - "5005:5005"
    command: gunicorn --chdir /app/rabbit_tr_results/flask --bind 0.0.0.0:5005 app:app