ALL_CHROMOSOMES:
- 1a
- '2'
- '3'
- '4'
- '5'
- '6'
- 7b
- '8'
- '9'
- '10'
- '11'
- '12'
- '13'
- '14'
- '15'
- '16'
- '17'
- '18'
- '19'
- '20'
- '21'
- 22a
- '23'
- '24'
- '25'
- X
ASSEMBLY_CHROMOSOMES:
- '13'
- '17'
- 22a
BUSCO_DATASET: primates_odb10
FLANKING_GENES:
- SALL2
- DAD1
- MGAM2
- EPHB6
- EPDR1
- VPS41
HAPLOTYPES:
- 1
- 2
RSS_LAYOUT:
  TRAJ:
    '12':
      +: start_minus
      '-': end_plus
  TRAV:
    '23':
      +: end_plus
      '-': start_minus
  TRBD:
    '12':
      +: start_minus
      '-': end_plus
    '23':
      +: end_plus
      '-': start_minus
  TRBJ:
    '12':
      +: start_minus
      '-': end_plus
  TRBV:
    '23':
      +: end_plus
      '-': start_minus
  TRDD:
    '12':
      +: start_minus
      '-': end_plus
    '23':
      +: end_plus
      '-': start_minus
  TRDJ:
    '12':
      +: start_minus
      '-': end_plus
  TRDV:
    '23':
      +: end_plus
      '-': start_minus
  TRGJ:
    '12':
      +: start_minus
      '-': end_plus
  TRGV:
    '23':
      +: end_plus
      '-': start_minus
RSS_LENGTH:
  '12': 28
  '23': 39
RSS_MERS:
  '12':
  - 9
  - 7
  '23':
  - 7
  - 9
SPECIES:
  cell: TR
  genome: GCF_006542625.1
  name: Nomascus leucogenys
