ALL_CHROMOSOMES:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
  - 16
  - 17
  - 18
  - 19
  - 20
  - "X"
  - "Y"

HAPLOTYPES: 
  - 1
  - 2

BUSCO_DATASET:
  primates_odb10

ASSEMBLY_CHROMOSOMES: 
  - 3
  - 7

SPECIES:
  name:
    "macaca mulatta"
  genome:
    GCF_003339765.1
  cell:
    TR

FLANKING:
  chr7:
    alpha-delta:
      start: SALL2
      end: DAD1
  chr3:
    beta:
      start: MGAM2
      end: TRPV6
    gamma:
      start: VPS41
      end: EPDR1

RSS_LAYOUT:
  TRAV:
    "23":
      "+": end_plus
      "-": start_minus
  TRAJ:
    "12":
      "+": start_minus
      "-": end_plus
  TRBV:
    "23":
      "+": end_plus
      "-": start_minus
  TRBD:
    "12":
      "+": start_minus
      "-": end_plus
    "23":
      "+": end_plus
      "-": start_minus
  TRBJ:
    "12":
      "+": start_minus
      "-": end_plus
  TRGV:
    "23":
      "+": end_plus
      "-": start_minus
  TRGJ:
    "12":
      "+": start_minus
      "-": end_plus
  TRDV:
    "23":
      "+": end_plus
      "-": start_minus
  TRDD:
    "12":
      "+": start_minus
      "-": end_plus
    "23":
      "+": end_plus
      "-": start_minus
  TRDJ:
    "12":
      "+": start_minus
      "-": end_plus

RSS_LENGTH:
  "12": 28
  "23": 39

RSS_MERS:
  "12": 
    - 9
    - 7
  "23": 
    - 7
    - 9

LIBRARY:
  species: 
    macaca mulatta
  cell_type: 
    TCR